# Generated by Django 4.2.17 on 2024-12-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'customMigration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
