# Generated by Django 4.2.17 on 2024-12-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_alter_job_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
